#!/usr/bin/env bash
# Runs every .sql file beside this script and writes the results to README.md.
# Lives in queries/; runs DuckDB from queries/, so the relative paths in the
# .sql files ('../json/...') work the same whether this script runs them or
# you do by hand.
set -euo pipefail

cd "$(dirname "$0")"

DUCKDB="${DUCKDB:-duckdb}"
OUT="README.md"

command -v "$DUCKDB" >/dev/null || {
  echo "duckdb not found. Set DUCKDB=/path/to/duckdb or install it." >&2
  exit 1
}

# Keeps only the final markdown table in a DuckDB run, discarding the row-count
# tables that CREATE TABLE statements emit.
last_table() {
  awk '
    # A separator row marks a new table; the line above it is its header.
    /^\|[-: |]+\|[[:space:]]*$/ { n = 0; delete L; L[++n] = prev; L[++n] = $0
                                  prev = $0; next }
    /^\|/                       { if (n) L[++n] = $0; prev = $0; next }
                                { prev = $0 }
    END { for (i = 1; i <= n; i++) print L[i] }
  '
}

# DuckDB writes every separator cell as ---, so numeric columns are detected
# here and given a trailing colon to right-align them on GitHub.
align_numeric() {
  awk -F'|' '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    { rows[NR] = $0; nf[NR] = NF; for (i = 1; i <= NF; i++) cell[NR, i] = trim($i) }
    NR > 2 { for (i = 2; i < NF; i++) if (cell[NR, i] != "" &&
               cell[NR, i] !~ /^-?[0-9,]+(\.[0-9]+)?$/) text[i] = 1 }
    END {
      for (r = 1; r <= NR; r++) {
        if (r != 2) { print rows[r]; continue }
        line = "|"
        for (i = 2; i < nf[r]; i++) line = line (i in text ? " --- |" : " ---: |")
        print line
      }
    }
  '
}

# GitHub builds heading anchors by lowercasing, dropping punctuation, and
# turning each space into a hyphen. Mirror that so the TOC links resolve.
slug() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/[^a-z0-9 _-]//g' -e 's/ /-/g'
}

# Sections are collected here first: the table of contents needs every heading
# before the body can be written out.
body="$(mktemp)"
trap 'rm -f "$body"' EXIT
toc=()

shopt -s nullglob
for sql in *.sql; do
  name="$(basename "$sql" .sql)"
  # Section title comes from the query's own leading -- comment.
  title="$(sed -n '1{s/^--[[:space:]]*//p;}' "$sql")"
  [ -n "$title" ] || title="$name"

  toc+=("- [$title](#$(slug "$title"))")

  echo "Running $name" >&2

  {
    echo "## $title"
    echo
    # Optional prose: <name>.md is included verbatim if present.
    [ -f "$name.md" ] && { cat "$name.md"; echo; }
    echo "<details><summary>SQL — <code>$sql</code></summary>"
    echo
    echo '```sql'
    cat "$sql"
    # Files saved without a final newline would put the closing fence on the
    # query's last line, leaving the code block open on GitHub.
    [ -z "$(tail -c1 "$sql")" ] || echo
    echo '```'
    echo
    echo "</details>"
    echo
    "$DUCKDB" -markdown < "$sql" | last_table | align_numeric
    echo
  } >> "$body"
done

{
  echo "# Query results"
  echo
  echo "Generated by \`generate_readme.sh\` — edit the .sql files, not this page."
  echo
  echo "Each query reads the JSON in \`../json\`. To run one yourself:"
  echo
  echo '```sh'
  echo "cd queries && duckdb < chapters_with_most_passages_referenced.sql"
  echo '```'
  echo
  # A one-entry contents list is just the heading again, so skip it.
  if [ "${#toc[@]}" -gt 1 ]; then
    printf '%s\n' "${toc[@]}"
    echo
  fi
} > "$OUT"

cat "$body" >> "$OUT"

echo "Wrote $(pwd)/$OUT" >&2
